export const SET_INITIAL_DATA = 'SET_INITIAL_DATA';
export const SET_CONSTRUCTION_ABOVE_THE_PIPE = 'SET_CONSTRUCTION_ABOVE_THE_PIPE';
export const SET_CONSTRUCTION_UNDER_THE_PIPE = 'SET_CONSTRUCTION_UNDER_THE_PIPE';
export const GET_INITIAL_DATA_REQUEST = 'GET_INITIAL_DATA_REQUEST';
export const GET_CONSTRUCTION_DATA_REQUEST = 'GET_CONSTRUCTION_DATA_REQUEST';