export const SET_HEAT_FLOW = 'SET_HEAT_FLOW';
export const SET_RESISTANCE = 'SET_RESISTANCE';
export const SET_H0_ABOVE_THE_PIPE = 'SET_H0_ABOVE_THE_PIPE';
export const SET_H0_UNDER_THE_PIPE = 'SET_H0_UNDER_THE_PIPE';
